- name: copy catalogue.service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
    remote_src: yes
  
- name: daemon reload 
  ansible.builtin.systemd_service:
    daemon_reload: true
    
- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes 