
- name: roboshop user add
  ansible.builtin.user:
    name: roboshop

- name: recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent 
    

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download "{{component}}"
  ansible.builtin.get_url:
    url:  https://roboshop-builds.s3.amazonaws.com/"{{component}}".zip
    dest: /tmp

- name: Extract "{{component}}" file
  ansible.builtin.unarchive:
    src: /tmp/"{{component}}".zip
    dest: /app
    remote_src: yes