
- name: roboshop user add
  ansible.builtin.user:
    name: roboshop

- name: recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent 
    

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download catalogue
  ansible.builtin.get_url:
    url:  https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp

- name: Extract catalogue file
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes