- name: copy mongodb.repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb-org-shell
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: count categories
  ansible.builtin.shell:  mongo --host mongodb.kamishetti.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component == "catalogue"

- name: count categories
  ansible.builtin.shell:  mongo --host mongodb.kamishetti.online --quiet --eval 'db = db.getSiblingDB("cart"); db.products.count()'
  register: product_count
  when: component == "cart"

- name: "load {{component}} data"
  ansible.builtin.shell: "mongo --host mongodb.kamishetti.online < /app/schema/{{component}}.js"
  when: product_count.stdout == "0"